from datetime import date

SAMPLE_ENVIRONMENTS = [
    {
        "id": "env-1",
        "name": "Living Room Window Nook",
        "location_type": "indoor",
        "light_level": "bright_indirect",
        "humidity_level": "medium",
        "temperature_range": "68-76",
        "airflow_level": "gentle",
        "distance_from_window": "2 ft",
        "notes": "Gets morning light and stable afternoon temps.",
    },
    {
        "id": "env-2",
        "name": "Office Shelf",
        "location_type": "indoor",
        "light_level": "low",
        "humidity_level": "low",
        "temperature_range": "66-72",
        "airflow_level": "low",
        "distance_from_window": "8 ft",
        "notes": "Shaded area with AC airflow nearby.",
    },
]

SAMPLE_PLANTS = [
    {
        "id": "plant-1",
        "nickname": "Milo",
        "common_name": "Pothos",
        "species_name": "Epipremnum aureum",
        "category": "trailing",
        "date_acquired": str(date.today()),
        "pot_size": "6 in",
        "soil_type": "well_draining_mix",
        "drainage_quality": "good",
        "environment_id": "env-1",
        "notes": "Fast grower, rotate weekly.",
    },
    {
        "id": "plant-2",
        "nickname": "Luna",
        "common_name": "Snake Plant",
        "species_name": "Dracaena trifasciata",
        "category": "succulent_like",
        "date_acquired": str(date.today()),
        "pot_size": "8 in",
        "soil_type": "cactus_mix",
        "drainage_quality": "excellent",
        "environment_id": "env-2",
        "notes": "Very forgiving plant.",
    },
]

SAMPLE_SPECIES = [
    {
        "id": "sp-1",
        "common_name": "Golden Pothos",
        "scientific_name": "Epipremnum aureum",
        "description": "A resilient trailing vine that adapts to many indoor spaces.",
        "difficulty": "easy",
        "light": "low_to_bright_indirect",
        "water": "moderate",
        "humidity": "medium",
        "pet_safe": False,
        "tags": ["beginner-friendly", "low-light", "trailing"],
        "image_url": "https://picsum.photos/seed/pothos/600/400",
        "category": "trailing",
        "preferred_light": ["low", "medium", "bright_indirect"],
        "preferred_humidity": ["medium", "high"],
        "preferred_temp": [65, 85],
        "watering_difficulty": 2,
        "beginner_friendliness": 5,
    },
    {
        "id": "sp-2",
        "common_name": "Snake Plant",
        "scientific_name": "Dracaena trifasciata",
        "description": "Architectural leaves and excellent drought tolerance.",
        "difficulty": "easy",
        "light": "low_to_direct",
        "water": "low",
        "humidity": "low_to_medium",
        "pet_safe": False,
        "tags": ["beginner-friendly", "low-light", "drought-tolerant"],
        "image_url": "https://picsum.photos/seed/snake/600/400",
        "category": "succulent_like",
        "preferred_light": ["low", "medium", "bright_indirect", "direct"],
        "preferred_humidity": ["low", "medium"],
        "preferred_temp": [60, 85],
        "watering_difficulty": 1,
        "beginner_friendliness": 5,
    },
    {
        "id": "sp-3",
        "common_name": "Peace Lily",
        "scientific_name": "Spathiphyllum wallisii",
        "description": "Lush foliage with occasional white blooms.",
        "difficulty": "moderate",
        "light": "medium_to_bright_indirect",
        "water": "moderate",
        "humidity": "high",
        "pet_safe": False,
        "tags": ["flowering", "low-light"],
        "image_url": "https://picsum.photos/seed/lily/600/400",
        "category": "tropical",
        "preferred_light": ["medium", "bright_indirect"],
        "preferred_humidity": ["medium", "high"],
        "preferred_temp": [65, 82],
        "watering_difficulty": 3,
        "beginner_friendliness": 3,
    },
    {
        "id": "sp-4",
        "common_name": "ZZ Plant",
        "scientific_name": "Zamioculcas zamiifolia",
        "description": "Glossy foliage and one of the easiest low-light plants.",
        "difficulty": "easy",
        "light": "low_to_bright_indirect",
        "water": "low",
        "humidity": "low_to_medium",
        "pet_safe": False,
        "tags": ["beginner-friendly", "low-light", "drought-tolerant"],
        "image_url": "https://picsum.photos/seed/zz/600/400",
        "category": "foliage",
        "preferred_light": ["low", "medium", "bright_indirect"],
        "preferred_humidity": ["low", "medium"],
        "preferred_temp": [62, 84],
        "watering_difficulty": 1,
        "beginner_friendliness": 5,
    },
    {
        "id": "sp-5",
        "common_name": "Spider Plant",
        "scientific_name": "Chlorophytum comosum",
        "description": "Classic hanging plant with striped arching leaves.",
        "difficulty": "easy",
        "light": "medium_to_bright_indirect",
        "water": "moderate",
        "humidity": "medium",
        "pet_safe": True,
        "tags": ["beginner-friendly", "pet-safe", "trailing"],
        "image_url": "https://picsum.photos/seed/spider/600/400",
        "category": "trailing",
        "preferred_light": ["medium", "bright_indirect"],
        "preferred_humidity": ["medium"],
        "preferred_temp": [60, 82],
        "watering_difficulty": 2,
        "beginner_friendliness": 4,
    },
    {
        "id": "sp-6",
        "common_name": "Monstera",
        "scientific_name": "Monstera deliciosa",
        "description": "Bold split leaves and strong statement growth.",
        "difficulty": "moderate",
        "light": "bright_indirect",
        "water": "moderate",
        "humidity": "medium_to_high",
        "pet_safe": False,
        "tags": ["beginner-friendly", "statement"],
        "image_url": "https://picsum.photos/seed/monstera/600/400",
        "category": "tropical",
        "preferred_light": ["bright_indirect"],
        "preferred_humidity": ["medium", "high"],
        "preferred_temp": [65, 84],
        "watering_difficulty": 3,
        "beginner_friendliness": 3,
    },
    {
        "id": "sp-7",
        "common_name": "String of Pearls",
        "scientific_name": "Curio rowleyanus",
        "description": "A cascading succulent with bead-like leaves.",
        "difficulty": "hard",
        "light": "bright_indirect_to_direct",
        "water": "low",
        "humidity": "low",
        "pet_safe": False,
        "tags": ["trailing", "drought-tolerant"],
        "image_url": "https://picsum.photos/seed/pearls/600/400",
        "category": "succulent_like",
        "preferred_light": ["bright_indirect", "direct"],
        "preferred_humidity": ["low"],
        "preferred_temp": [68, 82],
        "watering_difficulty": 4,
        "beginner_friendliness": 2,
    },
    {
        "id": "sp-8",
        "common_name": "Boston Fern",
        "scientific_name": "Nephrolepis exaltata",
        "description": "Feathery fronds that thrive with moisture and humidity.",
        "difficulty": "moderate",
        "light": "bright_indirect",
        "water": "high",
        "humidity": "high",
        "pet_safe": True,
        "tags": ["terrarium-friendly", "pet-safe"],
        "image_url": "https://picsum.photos/seed/fern/600/400",
        "category": "fern",
        "preferred_light": ["medium", "bright_indirect"],
        "preferred_humidity": ["high"],
        "preferred_temp": [62, 78],
        "watering_difficulty": 4,
        "beginner_friendliness": 2,
    },
    {
        "id": "sp-9",
        "common_name": "Aloe Vera",
        "scientific_name": "Aloe barbadensis miller",
        "description": "Sun-loving succulent used for decorative and practical purposes.",
        "difficulty": "easy",
        "light": "direct",
        "water": "low",
        "humidity": "low",
        "pet_safe": False,
        "tags": ["drought-tolerant", "beginner-friendly"],
        "image_url": "https://picsum.photos/seed/aloe/600/400",
        "category": "succulent_like",
        "preferred_light": ["direct"],
        "preferred_humidity": ["low"],
        "preferred_temp": [60, 90],
        "watering_difficulty": 1,
        "beginner_friendliness": 5,
    },
    {
        "id": "sp-10",
        "common_name": "Calathea",
        "scientific_name": "Goeppertia orbifolia",
        "description": "Patterned foliage plant that prefers humidity and consistency.",
        "difficulty": "hard",
        "light": "medium",
        "water": "moderate",
        "humidity": "high",
        "pet_safe": True,
        "tags": ["pet-safe", "statement"],
        "image_url": "https://picsum.photos/seed/calathea/600/400",
        "category": "tropical",
        "preferred_light": ["medium", "bright_indirect"],
        "preferred_humidity": ["high"],
        "preferred_temp": [66, 80],
        "watering_difficulty": 5,
        "beginner_friendliness": 1,
    },
    {
        "id": "sp-11",
        "common_name": "Jade Plant",
        "scientific_name": "Crassula ovata",
        "description": "Slow-growing succulent that enjoys bright light and dry roots.",
        "difficulty": "easy",
        "light": "bright_indirect_to_direct",
        "water": "low",
        "humidity": "low",
        "pet_safe": False,
        "tags": ["beginner-friendly", "drought-tolerant"],
        "image_url": "https://picsum.photos/seed/jade/600/400",
        "category": "succulent_like",
        "preferred_light": ["bright_indirect", "direct"],
        "preferred_humidity": ["low"],
        "preferred_temp": [62, 84],
        "watering_difficulty": 1,
        "beginner_friendliness": 4,
    },
    {
        "id": "sp-12",
        "common_name": "English Ivy",
        "scientific_name": "Hedera helix",
        "description": "A versatile trailing vine with classic leaf shapes.",
        "difficulty": "moderate",
        "light": "medium_to_bright_indirect",
        "water": "moderate",
        "humidity": "medium",
        "pet_safe": False,
        "tags": ["trailing", "low-light"],
        "image_url": "https://picsum.photos/seed/ivy/600/400",
        "category": "trailing",
        "preferred_light": ["medium", "bright_indirect"],
        "preferred_humidity": ["medium"],
        "preferred_temp": [55, 78],
        "watering_difficulty": 3,
        "beginner_friendliness": 3,
    },
]
